CREATE TABLE Aplicaciones (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    UsuarioID INT NOT NULL,
    OfertaID INT NOT NULL,
    FechaAplicacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (UsuarioID) REFERENCES Usuarios(ID),
    FOREIGN KEY (OfertaID) REFERENCES Ofertas(ID)
);
