CREATE TABLE Ofertas (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Titulo VARCHAR(255) NOT NULL,
    Descripcion TEXT NOT NULL,
    Categoria VARCHAR(50) NOT NULL,
    FechaPublicacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Activa BOOLEAN DEFAULT TRUE
);
